### ISSUE TITLE
cant connect get an error

### ISSUE THREAD

**Issue by johnnereth** [nathanoertel/whmcs-opensrsemail#3]
Hi Nathan, thanks for your module, i just wanted to add this comment

i was getting this error:  Communication error, please contact the administrator.

and found it was port 51000 tcp OUT was not setup yet in my firewall (other opensrs ports were already open but this one was not)

maybe you could add to the instructions.

thanks!

John

**Comment by nathanoertel** [comment]
Added it in.  Thanks.

**Comment by johnnereth** [comment]
thanks! Well for me actually that didnt solve the issue. Ive still got something in my firewall blocking the connection, trying to figure it out (I only thought it worked because I tried when the iptables were still getting flushed)  thanks for the fast reply.

i get invalid login when the firewall is rebooting as well, I am supposed to use the MAC login info correct?  does it matter if the domain is the default one opensrs setup that ends in .adm?

edit to add i see this error in my admin error log for whmcs

[10-Apr-2015 15:58:38 America/Toronto] ssl://admin.a.hostedemail.com
[10-Apr-2015 15:58:38 America/Toronto] ssl://admin.a.hostedemail.com

thanks

**Comment by johnnereth** [comment]
let me know if you have any thoughts as i cant get it to work. Ican get the opensrs domains pro to connect correctly still get the error, i can only get past it when restarting the firewall so there is something blocking the connection and all i see is that error in the logs 

[10-Apr-2015 15:58:38 America/Toronto] ssl://admin.a.hostedemail.com

to be clear are we entering the MAC admin login info such as domain@domain.adm  or the opensrs admin login info?

thanks!

**Comment by nathanoertel** [comment]
You are using the MAC admin login info.  It wouldn't seem like that would be your issue since it is only when your firewall is up that it isn't able to connect.

It uses port 4449.  It makes the call in servers/opensrsemail/opensrs/openSRS_mail.php starting on line 185.  You will see several points where exceptions are thrown when communication fails.  Are you capable of debugging that to find where it breaks down from there?  My guess is that it is just a firewall/port issue since you say it does work when that is off.

**Comment by johnnereth** [comment]
thanks for the port! opensrs could not tell me that one was needed unfortunately... that clears the first error thanks. Now I just get invalid login. and this error still shows up in the error log

[12-Apr-2015 19:51:40 America/Toronto] ssl://admin.a.hostedemail.com

so ive used both a new admin login that i created as well as the default one issued to me by opensrs

the domain@domain.adm one and I still get invalid login even though those details are correct (tested  that they are correct by logging into the admin.hostedemail.com interface)

thanks for your help!

**Comment by nathanoertel** [comment]
Have you verified that you are on cluster A? You would get that error if you tried to log into the wrong cluster.

**Comment by johnnereth** [comment]
Hi Nathan, yes I did (and checked with them as well) because if i tried logging in online it would not let me if i was on B. 
thanks

**Comment by nathanoertel** [comment]
What operation are you trying to do? The only reasons that I am aware of that would cause the invalid login are if you are using the wrong credentials, on the wrong cluster or attempting to modify a domain that you don't have access to. 

The message in the error log isn't an error, I will remove that tomorrow, it is something that I used for debugging and forgot to remove.

**Comment by johnnereth** [comment]
Hi Nathan

i am just trying to view the clients info in the whmcs (client admin area...services.... my services... click on manage for the email only service and on the screen that shows the management for the email  (add mailbox, add forwarding etc...) just below that it says login invalid

i wonder if it has something to do with not being able to modify the account. Not sure how to sovle that though

when i login to the admin interface with the credentials it shows me the list of domains that I am able to view and edit, but maybe i am missing a step in connecting them together? the use is listed as an admin for the domain in question. I can always send you a video of my settings and process if you want (privately)

thanks for your further help really appreciate it!

**Comment by nathanoertel** [comment]
Feel free to send me a video and I'll take a look and see if there is anything I can figure out from that.

To test it, you could try to swap out the list mailboxes function with the list domains function since that would only need the permissions of the account and you could determine if the credentials can log in at all.  You could also try to create a domain since that wouldn't require specific access to a domain, just access to be an admin.  That would let you know if it was an issue with logging into the account period or if it is specific about access to that domain.

**Comment by johnnereth** [comment]
thanks. I'm not sure how to swam out the functions you mentioned,  but i did try a test with a new domain and no luck so it seems like an issue logging in period. Can you let me know how to email you the video privately? maybe send my your twitter then i can PM you?

also its not the firewall now as i just double checked by turning it off for a second.
thanks!

**Comment by nathanoertel** [comment]
The same twitter name, @nathanoertel, otherwise you can look in the logs and find it with `git log` from where you cloned it.

**Comment by johnnereth** [comment]
Ok thanks I thought so but wasn’t sure, ive just followed you if you could do the same I can sent you a private link

Thanks!

Also no idea what you mean by 

otherwise you can look in the logs and find it with git log from where you cloned it.

sorry I am not a programmer, I just sort of stumble my way through troubleshooting

thanks!!

John

**Comment by johnnereth** [comment]
ok so the solution is to not use the full username (email) issued to you as an admin so if its

admin@yourdomain.adm only use "admin" in the username field.

thanks Nathan for solving it!
