### ISSUE TITLE
Module is no longer working with WHMCS 6.0.1

### ISSUE THREAD

**Issue by smileglobal** [nathanoertel/whmcs-opensrsemail#4]
Hi there,

Just setup a dev WHMCS server running WHMCS 6, then updated to 6.0.1 and it appears that this module is no longer working. Tried with several different themes, but when I log in as a customer the ability to add/delete mailboxes, view mailboxes, etc are no longer present.

Here is the error I am seeing in the Activity Log:

Smarty Error: Syntax error in template "/var/www/html/whmcs/modules/servers/opensrsemail/mailbox.tpl" on line 12 "{foreach from=$error item=error}" item variable 'error' may not be the same variable as at 'from'

as well as this:

Smarty Error: Syntax error in template "/var/www/html/whmcs/modules/servers/opensrsemail/mailboxes.tpl" on line 37 "{foreach from=$error item=error}" item variable 'error' may not be the same variable as at 'from'

Any ideas? Huge fan of this module and want to be able to continue using it with the latest version of WHMCS. Also, purchased a theme called "Web hoster" from ThemeMetro.com --- anything special need to happen in order for this module to work properly with that theme? The theme is 6.0.1 compliant.

Thanks!

Casey Price
Smile Global

**Comment by nathanoertel** [comment]
I just put up an update that should address the error you are seeing.  I am not going to have a chance to test with version 6 for a little while so please let me know if that resolves any errors of if you see other ones.  I am happy to get them resolved.  Let me know.

**Comment by smileglobal** [comment]
Nathan,

That fixed it! Thank you for taking care of this so quickly. Much
appreciated!!

Have a great weekend. Keep up the great work.

On a side note -- do you have any plans to create a similar module for
WHMCS to manage OpenSRS DNS? That would sure be cool!

Take care,

_--Casey James Price
*_A+/Network+ Certified*

360.298.0394

www.smileglobal.com

 https://twitter.com/Smile_Global https://www.facebook.com/smileglobal

**Comment by nathanoertel** [comment]
Glad that sorted it out.

Unfortunately not at the moment on the DNS front.  I could use that myself so I'll let you know if I start working on it.
